### ISSUE TITLE
Keeps asking for CAPTCHAs

### ISSUE THREAD

**Issue by M4X1K02** [AlexisN94/Skyscraper#4]
The captcha prompt keeps popping up, even after clearing them multiple times.
Only once did the CAPTCHA work and let through 3 results, which obviously is not enough.

I'll also include the errors that were appearing on the server, in case they might be helpful:
```npm
> server@0.0.0 start
> ts-node -T ./src/app.ts

Error: Evaluation failed: Failed to find elemenent with query: ".FqsTabs_tooltipTargetContainer__YjU5N:nth-child(1) > button"
    at ExecutionContext._ExecutionContext_evaluate (C:\Users\maxik\Documents\Projects\GithubProjects\Skyscraper\server\node_modules\puppeteer\src\common\ExecutionContext.ts:294:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (C:\Users\maxik\Documents\Projects\GithubProjects\Skyscraper\server\node_modules\puppeteer\src\common\ExecutionContext.ts:137:12)
    at async SkyscannerParser.selectFlightCategory (C:\Users\maxik\Documents\Projects\GithubProjects\Skyscraper\server\src\services\parsers\skyscanner-parser.ts:87:5)
    at async Scraper.getFlightDetails (C:\Users\maxik\Documents\Projects\GithubProjects\Skyscraper\server\src\services\scraper.ts:76:13)
    at async getFlights (C:\Users\maxik\Documents\Projects\GithubProjects\Skyscraper\server\src\routes\flights.ts:10:3)
Error: Evaluation failed: Failed to find elemenent with query: ".FqsTabs_tooltipTargetContainer__YjU5N:nth-child(1) > button"
    at ExecutionContext._ExecutionContext_evaluate (C:\Users\maxik\Documents\Projects\GithubProjects\Skyscraper\server\node_modules\puppeteer\src\common\ExecutionContext.ts:294:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (C:\Users\maxik\Documents\Projects\GithubProjects\Skyscraper\server\node_modules\puppeteer\src\common\ExecutionContext.ts:137:12)
    at async SkyscannerParser.selectFlightCategory (C:\Users\maxik\Documents\Projects\GithubProjects\Skyscraper\server\src\services\parsers\skyscanner-parser.ts:87:5)
    at async Scraper.getFlightDetails (C:\Users\maxik\Documents\Projects\GithubProjects\Skyscraper\server\src\services\scraper.ts:76:13)
    at async getFlights (C:\Users\maxik\Documents\Projects\GithubProjects\Skyscraper\server\src\routes\flights.ts:10:3)
Error: Evaluation failed: Failed to find elemenent with query: ".FqsTabs_tooltipTargetContainer__YjU5N:nth-child(1) > button"
    at ExecutionContext._ExecutionContext_evaluate (C:\Users\maxik\Documents\Projects\GithubProjects\Skyscraper\server\node_modules\puppeteer\src\common\ExecutionContext.ts:294:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (C:\Users\maxik\Documents\Projects\GithubProjects\Skyscraper\server\node_modules\puppeteer\src\common\ExecutionContext.ts:137:12)
    at async SkyscannerParser.selectFlightCategory (C:\Users\maxik\Documents\Projects\GithubProjects\Skyscraper\server\src\services\parsers\skyscanner-parser.ts:87:5)
    at async Scraper.getFlightDetails (C:\Users\maxik\Documents\Projects\GithubProjects\Skyscraper\server\src\services\scraper.ts:76:13)
    at async getFlights (C:\Users\maxik\Documents\Projects\GithubProjects\Skyscraper\server\src\routes\flights.ts:10:3)
e [AggregateError: All promises were rejected]
e [AggregateError: All promises were rejected]
```

I suspect they ramped up their bot detection.

Some things that might help:
- switching user agents
- reducing frequency

**Comment by AlexisN94** [comment]
Yes I'm aware. It started happening yesterday. Sadly I don't have time these days to look into it 😕
